export const types = {
  ADD_TASK_REQUEST: "ADD_TASK_REQUEST",
  ADD_TASK_SUCCESS: "ADD_TASK_SUCCESS",
  ADD_TASK_FAILURE: "ADD_TASK_FAILURE",

  VIEW_ALL_TASKS_REQUEST: "VIEW_ALL_TASKS_REQUEST",
  VIEW_ALL_TASKS_SUCCESS: "VIEW_ALL_TASKS_SUCCESS",
  VIEW_ALL_TASKS_FAILURE: "VIEW_ALL_TASKS_FAILURE",

  UPDATE_TASK_ORDER_REQUEST: "UPDATE_TASK_ORDER_REQUEST",
  UPDATE_TASK_ORDER_SUCCESS: "UPDATE_TASK_ORDER_SUCCESS",
  UPDATE_TASK_ORDER_FAILURE: "UPDATE_TASK_ORDER_FAILURE",
};
